
# python wrapper for package github.com/tuananh/py-event-ruler within overall package event_ruler
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy build -output=src/event_ruler -vm=python3 -rename=true -no-make=true ./

# the following is required to enable dlopen to open the _go.so file
import os,sys,inspect,collections
try:
	import collections.abc as _collections_abc
except ImportError:
	_collections_abc = collections

cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
from . import _event_ruler
from . import go

os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from event_ruler import event_ruler
# and then refer to everything using event_ruler. prefix
# packages imported by this package listed below:




# ---- Types ---


#---- Enums from Go (collections of consts with same type) ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---


# ---- Interfaces ---


# ---- Structs ---


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---


# ---- Functions ---
def test_event_pattern(payload, pattern):
	"""Test_Event_Pattern(str payload, str pattern) bool, str"""
	return _event_ruler.event_ruler_Test_Event_Pattern(payload, pattern)


