name: Publish PyPI

on:
  release:
    types: [created]
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/event-ruler
    permissions:
      id-token: write 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Setup tools
      run: |
        make setup-tools
    - name: Build package
      run: |
        make build
    
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: dist/

    # - name: Publish package distributions to PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1